# Generated by Django 3.2.9 on 2021-11-19 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(auto_now_add=True, unique_for_month=True)),
                ('faturamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('despesas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balanco', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='despesas',
            name='empresa',
        ),
        migrations.AddField(
            model_name='despesas',
            name='fixo',
            field=models.BooleanField(default=None, help_text='Marque caso seja uma despesa que você tenha todo mês.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesas',
            name='nome',
            field=models.CharField(max_length=245),
        ),
        migrations.CreateModel(
            name='Faturamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fixo', models.BooleanField(help_text='Marque caso seja um faturamento que você tenha todo mês.')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentoFaturamento', to='app_mc.fechamentos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoFaturamento', to='app_mc.tipofaturamento')),
            ],
        ),
        migrations.AddField(
            model_name='despesas',
            name='mes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fechamentoDespesas', to='app_mc.fechamentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesas',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tipoDespesa', to='app_mc.tipodespesas'),
            preserve_default=False,
        ),
    ]
