# Generated by Django 3.2.9 on 2021-11-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mc', '0002_auto_20211118_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentos',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mc.fechamentos'),
        ),
        migrations.AlterField(
            model_name='fechamentos',
            name='balanco',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fechamentos',
            name='despesas',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fechamentos',
            name='faturamento',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
