# Generated by Django 3.2.9 on 2021-11-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mc', '0003_auto_20211119_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoDespesa', to='app_mc.tipodespesas'),
        ),
    ]
