# Generated by Django 3.2.9 on 2021-11-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mc', '0005_alter_despesas_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentos',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoFaturamento', to='app_mc.tipofaturamento'),
        ),
    ]
