# Generated by Django 3.2.9 on 2021-12-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mc', '0006_alter_faturamentos_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamentos',
            name='balanco',
        ),
        migrations.RemoveField(
            model_name='fechamentos',
            name='despesas',
        ),
        migrations.RemoveField(
            model_name='fechamentos',
            name='faturamento',
        ),
        migrations.AlterField(
            model_name='despesas',
            name='mes',
            field=models.ForeignKey(help_text='deixar automatico', on_delete=django.db.models.deletion.CASCADE, related_name='fechamentoDespesas', to='app_mc.fechamentos'),
        ),
        migrations.AlterField(
            model_name='faturamentos',
            name='mes',
            field=models.ForeignKey(help_text='deixar automatico', on_delete=django.db.models.deletion.CASCADE, related_name='fechamentoFaturamentos', to='app_mc.fechamentos'),
        ),
    ]
