# Generated by Django 4.0 on 2021-12-15 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mc', '0007_auto_20211211_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentoDespesas', to='app_mc.fechamentos'),
        ),
        migrations.AlterField(
            model_name='faturamentos',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentoFaturamentos', to='app_mc.fechamentos'),
        ),
    ]
