# Generated by Django 4.0 on 2021-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mc', '0008_alter_despesas_mes_alter_faturamentos_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
